### PR TITLE
Reorganize docs

### PR DESCRIPTION
**Pull request by singingwolfboy**
The docs for this project need some love. This is an attempt to rewrite and reorganize them to make them clearer and more approachable.

# How do I see how it looks?
1. Clone this repository, and switch to the `reorganize-docs` branch
2. `pip install -r requirements.txt -r dev-requirements.txt`
3. `cd docs`
4. `make html`
5. Open `_build/html/index.html` in your browser

# Major changes
* Removed all the provider-specific quickstart files, in favor of linking to provider-specific example projects such as [flask-dance-github](https://github.com/singingwolfboy/flask-dance-github) and [flask-dance-google](https://github.com/singingwolfboy/flask-dance-google)
* Renamed "backend" to "storage" (see #223)
* Rewrote testing documentation to reference `MemoryBackend` (which is what we use in the tests for this project) and [Betamax](https://betamax.readthedocs.io)
* Added the following docs: "concepts", "understanding the magic", and "contributing"
* Reorganized docs into "User Guide", "Options & Configuration", and "Advanced Topics" sections

I would love some help with this! Any thoughts, suggestions, or feedback would be greatly appreciated.

### CODE REVIEW

**Comment by singingwolfboy** [comment]
@daenney, could you take a look at this please? I'd love to hear your thoughts.

**Comment by daenney** [comment]
I will. I'm travelling this week though so I might be a bit slow to get back to you. I'll definitely have time next week.

**Comment by singingwolfboy** [comment]
That’s fine, there’s no hurry. Hope your travels go well!

**Comment by singingwolfboy** [comment]
@daenney Just a friendly reminder about this. Have you had time to take a look?

**Comment by daenney** [comment]
Yes I did. I think this makes sense. It got very busy with all the quickstart examples and most of them were nearly identical so this feels much cleaner.

Also happy to see the testing example get some love and be expanded :smile:.

**Pull request merged**
