### PR TITLE
Instagram OAuth

### PR DESCRIPTION
**Pull request by AdamGold**

### CODE REVIEW

**Comment by AdamGold** [comment]
Looking into why it doesn't recognize `instagram_compliance_fix`.

**Comment by singingwolfboy** [comment]
@AdamGold looks like the Instagram compliance fix has been merged into the GitHub project, but no one has created a new version and published it on PyPI with that code in it. Would you like me to do so?

**Comment by AdamGold** [comment]
@singingwolfboy That would be great :) I'm not a `requests-oauthlib` maintainer on PyPi, can't do it myself.

**Comment by AdamGold** [comment]
@singingwolfboy a friendly ping :)

**Comment by singingwolfboy** [comment]
@AdamGold whoops, sorry! I've tagged requests-oauthlib, and uploaded the new version to PyPI.

**Comment by AdamGold** [comment]
Is there any way to rerun the CI pipelines?

**Pull request closed without merging**
