### PR TITLE
Add Digital Ocean as a provider

### PR DESCRIPTION
**Pull request by mikeabrahamsen**
- add digitalocean.py to configure blueprint for provider
- add tests for Digital Ocean provider
- update CHANGELOG
- update docs/providers.rst
- add DigitalOcean to wordlist

Question:
The default scope with Digital Ocean is `read`. I left the default as `None` for library consistency, would it make sense in this case to change the default, or is this something we want the user to explicitly set?

### CODE REVIEW

**Comment by daenney** [comment]
We have at least 3 providers in `contrib` with a default for `scope` that's not `None`, including the recently added one for Strava. If having a scope of `None` doesn't really make sense for the DO provider, I'm happy to see that changed to `read`.

@singingwolfboy Do you have a preference here? It does feel like we're being a bit inconsistent by some providers having a default scope we set, whereas most have no scope at all. I personally prefer the idea of explicitly having to ask for scopes when using the `make_*_blueprint` functions, but there's value in a sensible default too.

**Comment by mikeabrahamsen** [comment]
I prefer explicitly setting the scope as well. I created an example repo of how to use this provider here: https://github.com/mikeabrahamsen/flask-dance-digitalocean-oauth-example

**Comment by singingwolfboy** [comment]
> It does feel like we're being a bit inconsistent by some providers having a default scope we set, whereas most have no scope at all.

Good point. However, that feels different from this specific provider. Let's open a separate issue to discuss the inconsistency across providers.

@mikeabrahamsen This looks great! Thank you for doing this :-)

**Comment by singingwolfboy** [comment]
This is now published in version 3.2.0.

**Pull request merged**
