### PR TITLE
Update for Discord moving to discord.com

### PR DESCRIPTION
**Pull request by fenhl**
Since [discordapp.com](https://discordapp.com/) is now a redirect to [discord.com](https://discord.com/) which additionally shows a notice about the address change every time you use it, this updates the provider so the new domain is used and the notice should no longer appear.

### CODE REVIEW

**Comment by daenney** [comment]
@singingwolfboy Our tests are broken I think. The change @fenhl made is unrelated to the test failures from what I can see.

**Comment by singingwolfboy** [comment]
You're absolutely right. I spent some time today fixing up our tests, and moving over from Travis CI to GitHub Actions. @fenhl, could you please rebase your branch, so that it picks up those changes? The tests should pass after that.

**Comment by fenhl** [comment]
Done.

**Comment by singingwolfboy** [comment]
Thank you! 😄

**Pull request merged**
