### PR TITLE
Added Okta support

### PR DESCRIPTION
**Pull request by tnolan8**
Was exploring using Okta for a project, came across Flask-Dance, decided to add support for it.

### CODE REVIEW

**Comment by tnolan8** [comment]
I just realised I should add a quickstart doc too.

**Comment by singingwolfboy** [comment]
This is a great start! Thanks for making this pull request -- I love when people want to help out with Flask-Dance. 😄 

However, please check [the README in the `contrib` directory](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/contrib/README.rst): it has a checklist of requirements for adding a new provider. You're missing a few: specifically, number 6 (documentation) and number 8 (changelog). Once you get those done, I can review this more closely, and hopefully get it merged.

**Comment by tnolan8** [comment]
Sure thing, I'll get those updated at some point this evening! Cheers for taking a look!

**Comment by singingwolfboy** [comment]
The best way to do that is to rebase your pull request. [Here's a guide on how to rebase pull requests](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request), if you're not familiar with the process.

**Comment by daenney** [comment]
@singingwolfboy We could also just sqash-merge it on our side, which would make the slightly odd git history disappear.

**Comment by daenney** [comment]
Aside from there not being a quickstart I think this is complete, no? Do we want to have a quickstart per provider?

**Comment by singingwolfboy** [comment]
Looks great!

**Comment by tnolan8** [comment]
Awesome cheers for that! Are you planning on cutting a new version any time soon? 🙂 also minor note, I've just noticed I added my change under the wrong heading on the CHANGELOG my bad.

**Comment by singingwolfboy** [comment]
> Are you planning on cutting a new version any time soon?

Yeah, I really should do that at some point... 😜I'm on vacation at the moment, but I'll be back on Monday. At that time, I'll look into cutting a new version. Alternatively, @daenney has the necessary permissions to cut a new release and push it to PyPI, and she is welcome to do so if she feels comfortable with it.

> I've just noticed I added my change under the wrong heading on the CHANGELOG my bad.

Send a pull request to fix it? 😅

**Comment by singingwolfboy** [comment]
@tnolan8: @tcmRyan is _really_ close to getting #170 merged, so I'm going to give him some time to do so before cutting a new version. Once that's in, I'll cut version 1.1.0. (Maybe you could send a PR to fix the changelog, as well?)

**Comment by singingwolfboy** [comment]
@tnolan8: Alright, [Flask-Dance 1.1.0 is published](https://pypi.org/project/Flask-Dance/1.1.0)! :tada: (I fixed the changelog for you, as well.)

**Comment by tnolan8** [comment]
@singingwolfboy Much appreciated!

**Pull request merged**
