### PR TITLE
Updated Azure to allow defining authorization_url_params

### PR DESCRIPTION
**Pull request by gchq83514**
I hope this is all okay. I have updated the Azure provider to allow someone to define authorization_url_params to pass additional data.

Azure supports extra parameters such as `prompt`, `login_hint` and `domain_hint`

https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code#request-an-authorization-code

### CODE REVIEW

**Comment by gchq83514** [comment]
The documentation test is failing, it seems that it is out of my control looking at the logs.

**Comment by singingwolfboy** [comment]
This is great! Thank you so much for doing this!

However, it sounds like your goal is being able to set `prompt`, `login_hint` and `domain_hint`. Why not add those to the argument list for `make_azure_blueprint()`, instead of making users understand where they need to set these values in the `authorization_url_params`?

For example, the Google blueprint does this for the `reprompt_consent`, `reprompt_select_account`, and `hosted_domain` arguments: https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/contrib/google.py#L86-L94

Does that seem closer to what you want? Or is there a reason why you want to allow users to set `authorization_url_params` dynamically?

**Comment by singingwolfboy** [comment]
Also, thanks for fixing the documentation tests! I've cherry-picked that commit onto the master branch, so you can remove it from this pull request. 😄

**Comment by gchq83514** [comment]
> This is great! Thank you so much for doing this!
> 
> However, it sounds like your goal is being able to set `prompt`, `login_hint` and `domain_hint`. Why not add those to the argument list for `make_azure_blueprint()`, instead of making users understand where they need to set these values in the `authorization_url_params`?
> 
> For example, the Google blueprint does this for the `reprompt_consent`, `reprompt_select_account`, and `hosted_domain` arguments: https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/contrib/google.py#L86-L94
> 
> Does that seem closer to what you want? Or is there a reason why you want to allow users to set `authorization_url_params` dynamically?

No problem!

The only argument I really need is `prompt` but thought I would include the others for peoples information.

I will add them to the argument list as you suggest.

Would you like me to do it under a new PR or keep this one open?

Thanks

**Comment by singingwolfboy** [comment]
You can rebase this pull request and make the changes here, or close this one and open a new one. Whichever you prefer -- it makes no difference to me!

**Comment by singingwolfboy** [comment]
Here's a handy guide for how to rebase, if you're not familiar with it: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by gchq83514** [comment]
> Here's a handy guide for how to rebase, if you're not familiar with it: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

Thanks for the link, I have rebased and will work on the aforementioned changes

**Comment by gchq83514** [comment]
All tests pass.

Hopefully this is okay. I couldn't implement exactly like the Google one using bools, as Azure SSO only allows one prompt not multiple.

Thanks

**Comment by gchq83514** [comment]
Hello,

Very valid point, I forgot people might not specify the param name when calling the function!

Hopefully this is now complete. Thanks

**Comment by singingwolfboy** [comment]
Fantastic! This is now merged, and released with Flask-Dance 3.0! 😄

**Comment by gchq83514** [comment]
Awesome, thank you! 😊

**Pull request merged**
