### PR TITLE
`pkg_resources.parse_version()` instead of `distutils.StrictVersion`

### LINKED ISSUE #53: StrictVersion check fails with Flask==0.11.dev0
```
  File "/home/.../.venv/lib64/python3.5/site-packages/flask_dance/consumer/base.py", line 37, in __init__
    if StrictVersion(flask.__version__) < StrictVersion('1.0'):
  File "/usr/lib64/python3.5/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib64/python3.5/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '0.11.dev0'
```

### PR DESCRIPTION
**Pull request by singingwolfboy**
`pkg_resources.parse_version()` is more flexible. Fixes #53.

@ThiefMaster, can you try this out and let me know if it works for you?

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Haven't tested it yet but I think Flask>=0.11 should be accepted since 0.11 is current master (which will be released as 1.0 eventually), so it's enough. I don't use `root_path` but no need to remove it in a version where it's supported. Or why not pass it only to the blueprint constructor if it's not None? That way setting it will fail if Flask is too old and work fine if not. I think that's better than silently ignoring the argument if it's not supported.

**Comment by singingwolfboy** [comment]
@ThiefMaster: good thought, I've updated the pull request.

**Comment by ThiefMaster** [comment]
thanks, works fine now!
could you release 0.8.3 by any chance after merging this? would be nice not having to switch to a git version to get the fix (right now i'm using a monkeypatch but that's awful and i'd rather not commit that if a new version fixes it properly)

**Comment by singingwolfboy** [comment]
I've released 0.8.3 with the fix.

**Comment by ThiefMaster** [comment]
great, thanks! if all projects/maintainers were that fast... ;)

**Pull request merged**
