### PR TITLE
Added the Azure AD pre-set configuration

### PR DESCRIPTION
**Pull request by steven-martins**
Hello,

I currently have project which needs an authentication with Azure AD and the v2.0 endpoint. So, I decided to create a new pre-set.

Regards,

Steven.

### CODE REVIEW

**Comment by singingwolfboy** [comment]
This looks great! However, can you take out the changes related to the version number, and put the changelog entry under "unreleased"? After this gets merged, I'll do the changes necessary for a new release of the project.

**Comment by singingwolfboy** [comment]
Also, what is "Azure AD", and how is it different from Azure in general? It looks to me like the code you've put in should work for any Azure service in general, but I'm not familiar with Azure.

**Comment by steven-martins** [comment]
I pushed a new commit to remove the version number.

AD is for "Active Directory", it's their authentication system / Users database. Every documentations of Microsoft append 	specifically "AD" when they talk about Single sign-on, oauth, etc. ... According to me "Azure" is more oriented to their cloud platform.

If you want, I can remove any mention of "AD" ?

**Comment by singingwolfboy** [comment]
Sorry for the delay -- I was on my phone when I first saw this pull request. Now that I've had some time to examine it more in-depth, and review Azure's documentation, I think this is all set. You're right that Microsoft refers to it as "Azure AD" everywhere in their documentation, so it makes sense to have the Flask-Dance documentation reflect that.

Thank you so much for the contribution! ✨ 🍰 ✨

**Comment by singingwolfboy** [comment]
I'll release a new version of Flask-Dance to PyPI in a few days -- I want to see if we can also get #62 in, as well. That pull request is waiting on a newly-released version of `requests-oauthlib`, which [the maintainer said he would do in a few days](https://github.com/requests/requests-oauthlib/pull/251#issuecomment-247850377). Once that's in, I'll cut and release Flask-Dance 0.10!

**Comment by singingwolfboy** [comment]
[Flask-Dance 0.10.0 is out!](https://pypi.python.org/pypi/Flask-Dance/0.10.0)

**Pull request merged**
