### PR TITLE
Bug: Fixed a small typo

### PR DESCRIPTION
**Pull request by nabinkhadka**
Fixes the following exception

`TypeError: 'name' is an invalid keyword argument for User`

### CODE REVIEW

**Comment by singingwolfboy** [comment]
Thanks for sending a pull request -- I really appreciate it! I'd love for more people to contribute to the documentation. :smile:

However, I don't think this change makes sense. The `User` model is defined by the developer writing the application, not by Flask-Dance. That model can have whatever fields the developer wants to define, including a "name" field for the user's name. That's what this example code is populating -- it get's the user's name from GitHub, and adds that to the "name" field in the local database. It's not about a username at all.

Does that make sense? Can you tell me why you thought this was supposed to be a username field?

**Comment by nabinkhadka** [comment]
@singingwolfboy This is because of this one https://flask-dance.readthedocs.io/en/latest/multi-user.html

**Comment by singingwolfboy** [comment]
@nabinkhadka, you just pointed to the rendered HTML version of the file you're modifying. I'm still not sure why you thought this was supposed to be a username field...

**Comment by nabinkhadka** [comment]
@singingwolfboy Because I had followed the whole tutorial and I was previously reading [this](https://flask-dance.readthedocs.io/en/latest/quickstarts/sqla-multiuser.html) as well. The link has "username"

**Pull request closed without merging**
