### PR TITLE
Add Strava.

### PR DESCRIPTION
**Pull request by HeMan**
- Add Strava as Oauth2 supplier.

### CODE REVIEW

**Comment by singingwolfboy** [comment]
Thanks! However, please make sure this pull request satisfies all points on the checklist in the README: https://github.com/singingwolfboy/flask-dance/blob/main/flask_dance/contrib/README.rst

Also, all tests on CI must pass, including formatting checkers like `black`.

**Comment by HeMan** [comment]
My code passes `black`, it's `flask-dance/flask_dance/consumer/requests.py` and `flask-dance/flask_dance/consumer/storage/sqla.py` that doesn't. My guess is that it's a newer black that is picky, and since it's not pinned it could trig at any time. 
I'll add test and update documentation and CHANGELOG.

**Comment by HeMan** [comment]
Updated with documentation and test. This PR will pass all CI tests once #328 is merged.

**Review by singingwolfboy — APPROVED** [review]
Looks great! Thank you ✨

**Pull request merged**
