### PR TITLE
Fix a warning in setup.py

### PR DESCRIPTION
**Pull request by felixonmars**
```
Warning: 'classifiers' should be a list, got type 'tuple'
```

### CODE REVIEW

**Comment by singingwolfboy** [comment]
How did you get this warning?

**Comment by felixonmars** [comment]
@singingwolfboy Just run "python setup.py" with or without any additional command. This may be coming from Python 3.7.

**Comment by felixonmars** [comment]
Update: found it, so it's indeed coming from Python 3.7: https://bugs.python.org/issue19610

**Comment by daenney** [comment]
I really don't understand why they decided that a tuple wasn't good enough now but :man_shrugging:.

**Pull request merged**
