### PR TITLE
Fix twitter blueprint configuration loading

### PR DESCRIPTION
**Pull request by Tadaboody**

### CODE REVIEW

**Comment by Tadaboody** [comment]
Fixes #198

**Comment by Tadaboody** [comment]
Note that the only test failing is the one I added.

**Comment by daenney** [comment]
Ehm. Adding a test that fails doesn't fix anything form my point of view. Is there a commit missing?

**Comment by singingwolfboy** [comment]
We can't merge pull requests until the automated tests pass. Since the author of this PR has been unresponsive, I'm closing this PR.

**Pull request closed without merging**
